### ISSUE TITLE
GSoC related

### ISSUE THREAD

**Issue by therahilshaikh** [hans2103/hans2103#1]
Hello, 
I want to apply for Joomla's project 
Project II: **Accessibility**
Project Description
Implement and improve several accessibility functions in Joomla! Keyboard navigation.
Could you please guide me on how to get started?

Thank you
Regards
Rahil Shaikh

**Comment by hans2103** [comment]
@therahilshaikh please go to the following sites:

- https://summerofcode.withgoogle.com/organizations/6713740117934080/
- https://community.joomla.org/gsoc-2021/gsoc-participant-13th-time-lucky.html
- https://magazine.joomla.org/all-issues/may-2021/gsoc-2021-candidates-announced
